# Generated by Django 4.2 on 2023-05-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linguauser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
