# Generated by Django 4.2 on 2023-05-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_user', '0003_alter_linguauser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='linguauser',
            name='account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
