# Generated by Django 4.2 on 2023-06-15 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mod_user', '0004_linguauser_account_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_at', models.DateTimeField()),
                ('user_to_validate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_validation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
