# Generated by Django 4.2 on 2023-07-23 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mod_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_user', '0005_validationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=mod_user.models.upload_pdp)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_current', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
