# Generated by Django 4.2 on 2023-07-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type_of',
            field=models.CharField(choices=[('OTA', 'Open To All'), ('IO', 'Invite Only')], default='OTA', max_length=3),
        ),
    ]
