# Generated by Django 4.2 on 2023-07-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_space', '0003_roominvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlanguage',
            name='room_language_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
