# Generated by Django 4.2 on 2023-07-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_space', '0005_roommessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommessage',
            name='room',
        ),
        migrations.AddField(
            model_name='roommessage',
            name='room_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mod_space.roomlanguage'),
            preserve_default=False,
        ),
    ]
