# Generated by Django 4.2 on 2023-07-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_organization', '0003_organization_created_at_organization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
